// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wdc.Sales.Orders.Api.Persistence;

#nullable disable

namespace Wdc.Sales.Orders.Api.Persistence
{
    [DbContext(typeof(OrdersDbContext))]
<<<<<<<< HEAD:Wdc.Sales.Orders.Api/Persistence/20250603192325_InitialCreate.Designer.cs
    [Migration("20250603192325_InitialCreate")]
    partial class InitialCreate
========
    [Migration("20250603184552_InitOrder")]
    partial class InitOrder
>>>>>>>> ad68230941517260077e96d409e97bc1228185c2:Wdc.Sales.Orders.Api/Persistence/20250603184552_InitOrder.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Wdc.Sales.Orders.Api.Entitys.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

<<<<<<<< HEAD:Wdc.Sales.Orders.Api/Persistence/20250603192325_InitialCreate.Designer.cs
                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
========
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");
>>>>>>>> ad68230941517260077e96d409e97bc1228185c2:Wdc.Sales.Orders.Api/Persistence/20250603184552_InitOrder.Designer.cs

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Wdc.Sales.Orders.Api.Entitys.OrderItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Wdc.Sales.Orders.Api.Entitys.OrderItem", b =>
                {
                    b.HasOne("Wdc.Sales.Orders.Api.Entitys.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Wdc.Sales.Orders.Api.Entitys.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
